# Generated by Django 3.1 on 2020-08-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='confirmation_sent_date',
            new_name='verification_sent_date',
        ),
    ]
