# Generated by Django 3.1 on 2020-08-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='release_date',
            new_name='publish_date',
        ),
    ]
