# Generated by Django 3.1 on 2020-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20200820_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-publish_date', '-issue_number']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
