name: Django Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade setuptools
        run: python -m pip install --upgrade pip setuptools
      - name: Install test dependencies
        run: python -m pip install coverage flake8 model-bakery tox
      - name: Run tox
        run: |
          python -m pip --version
          python -m tox --version
          python -m tox
      - name: Report Coverage
        run: |
          python -m coverage combine
          python -m coverage report -m
          python -m coverage xml
          python -m coverage html
      - name: Send coverage results
        uses: codecov/codecov-action@v1
